# Generated by Django 4.1.2 on 2022-10-15 15:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('c2b51dcb-d01f-44b6-bdee-8dc4661cd1db'), help_text='VPS instance uuid', unique=True, verbose_name='instance_uuid')),
                ('cpu', models.PositiveSmallIntegerField(help_text='Number of CPU cores', validators=[django.core.validators.MinValueValidator(1, 'Core count can not be less than one.')], verbose_name='CPU_core_count')),
                ('ram', models.PositiveSmallIntegerField(help_text='VPS instance RAM size in GB', validators=[django.core.validators.MinValueValidator(1, 'RAM size can not be less than one GB.'), django.core.validators.MaxValueValidator(128, 'RAM size can not be more than 128 GB.')], verbose_name='RAM_size_GB')),
                ('hdd', models.PositiveSmallIntegerField(help_text='VPS instance HDD size in GB', validators=[django.core.validators.MinValueValidator(32, 'HDD size can not be less than 32 GB.'), django.core.validators.MaxValueValidator(1024, 'HDD size can not be more than 1024 GB.')], verbose_name='HDD_size_GB')),
                ('status', models.CharField(choices=[('START', 'STARTED'), ('BLOCK', 'BLOCKED'), ('STOP', 'STOPPED')], help_text='VPS instance status', max_length=64, verbose_name='VPS_status')),
            ],
            options={
                'verbose_name': 'VPS_instance',
                'verbose_name_plural': 'VPS_instances',
                'ordering': ('-id',),
            },
        ),
    ]
