# Generated by Django 4.1.2 on 2022-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='uuid',
            field=models.UUIDField(help_text='VPS instance uuid', unique=True, verbose_name='instance_uuid'),
        ),
    ]
